dataset:
    dataset_name: AWA2
    GZSL: True
    data_path: /data/xingyu/Wasserstein_Autoencoders/data/AWA2
    save_path: /data/xingyu/gzsl_svae/experiments/AWA2_cls1.0
    
model:
    ifsample: False
    attr_size: 85
    input_size: 2048
    mid_size: 512
    hidden_size: 64
    classes: 150
train:
    epoch: 1000
    learning_rate: 1e-4
    batch_size: 128
    check_point: 0
    interval: 200
    save_every: 10
    